apiVersion: ratelimit.zufardhiyaulhaq.com/v1alpha1
kind: GlobalRateLimitConfig
metadata:
  name: istio-public-gateway
  namespace: istio-system
spec:
  type: "gateway"
  selector:
    labels:
      "istio": "ingressgateway"
    istio_version:
      - "1.12"
  ratelimit:
    spec:
      domain: "public-gateway"
      failure_mode_deny: true
      timeout: "10s"
      service:
        type: "service"
        name: "httpbin-ratelimit"